# Production values for go-web-app
# This file contains production-specific configurations

# Global settings
global:
  imageRegistry: "cleanstart.azurecr.io"
  imagePullSecrets:
    - name: acr-secret

# Image configuration
image:
  repository: cleanstart/go
  tag: "1.0.0"
  pullPolicy: IfNotPresent

# Service account
serviceAccount:
  create: true
  annotations:
    iam.gke.io/gcp-service-account: go-web-app@my-project.iam.gserviceaccount.com

# Pod security context
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1001
  runAsGroup: 1001
  fsGroup: 1001
  seccompProfile:
    type: RuntimeDefault

# Container security context
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1001
  runAsGroup: 1001
  capabilities:
    drop:
      - ALL

# Deployment configuration
replicaCount: 5

# Pod annotations
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8080"
  prometheus.io/path: "/metrics"
  cluster-autoscaler.kubernetes.io/safe-to-evict: "true"

# Service configuration
service:
  type: ClusterIP
  port: 8080
  targetPort: 8080
  protocol: TCP
  name: http
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"

# Ingress configuration
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "16m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "30"
    nginx.ingress.kubernetes.io/rate-limit: "1000"
    nginx.ingress.kubernetes.io/rate-limit-window: "1m"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  hosts:
    - host: go-app.production.example.com
      paths:
        - path: /
          pathType: Prefix
    - host: api.production.example.com
      paths:
        - path: /api
          pathType: Prefix
        - path: /health
          pathType: Prefix
        - path: /metrics
          pathType: Prefix
  tls:
    - secretName: go-app-tls-secret
      hosts:
        - go-app.production.example.com
        - api.production.example.com

# Resource configuration
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

# Autoscaling configuration
autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 20
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 70
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 10
          periodSeconds: 60
        - type: Pods
          value: 2
          periodSeconds: 60
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60
        - type: Pods
          value: 4
          periodSeconds: 60
      selectPolicy: Max

# Node selector
nodeSelector:
  kubernetes.io/os: linux
  node-type: production

# Tolerations
tolerations:
  - key: "production"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"

# Affinity
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - go-web-app
        topologyKey: kubernetes.io/hostname
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/os
              operator: In
              values:
                - linux

# Environment variables
env:
  # Application Configuration
  GIN_MODE: "release"
  GIN_DEBUG: "false"
  LOG_LEVEL: "INFO"
  
  # Database Configuration
  DB_PATH: "/app/data/users.db"
  DB_POOL_SIZE: "20"
  DB_POOL_TIMEOUT: "30"
  
  # Application Settings
  MAX_CONTENT_LENGTH: "16777216"  # 16MB
  SESSION_LIFETIME: "3600"  # 1 hour
  
  # Security Settings
  SECRET_KEY: "production-secret-key-change-me"
  CSRF_ENABLED: "true"
  CSRF_TIME_LIMIT: "3600"
  
  # Monitoring Configuration
  ENABLE_METRICS: "true"
  METRICS_PORT: "8080"
  HEALTH_CHECK_INTERVAL: "30"
  
  # Caching Configuration
  CACHE_TYPE: "memory"
  CACHE_DEFAULT_TIMEOUT: "300"
  
  # API Configuration
  API_RATE_LIMIT: "1000"
  API_RATE_LIMIT_WINDOW: "60"
  
  # Logging Configuration
  LOG_FORMAT: "%s - %s - %s - %s"
  LOG_FILE: "/app/logs/app.log"
  LOG_MAX_SIZE: "10485760"  # 10MB
  LOG_BACKUP_COUNT: "10"
  
  # Performance Configuration
  WORKER_THREADS: "8"
  WORKER_CONNECTIONS: "2000"
  KEEPALIVE_TIMEOUT: "65"
  
  # Feature Flags
  ENABLE_DEBUG_ENDPOINTS: "false"
  ENABLE_PROFILING: "false"
  ENABLE_CORS: "true"
  
  # External Services
  EXTERNAL_API_URL: "https://api.production.example.com"
  EXTERNAL_API_TIMEOUT: "30"
  
  # Application-specific settings
  APP_NAME: "Go Production App"
  APP_VERSION: "1.0.0"
  APP_DESCRIPTION: "Go application running on Kubernetes in production"
  
  # Timezone Configuration
  TZ: "UTC"
  
  # Go-specific settings
  GOROOT: "/usr/local/go"
  GOPATH: "/go"
  CGO_ENABLED: "0"
  GOOS: "linux"
  
  # Health Check Configuration
  HEALTH_CHECK_PATH: "/health"
  READINESS_CHECK_PATH: "/ready"
  LIVENESS_CHECK_PATH: "/health"
  
  # Graceful Shutdown Configuration
  GRACEFUL_SHUTDOWN_TIMEOUT: "30"
  SHUTDOWN_HANDLERS_ENABLED: "true"

# Secrets configuration
secrets:
  # Database Configuration
  database:
    url: "sqlite:///app/data/users.db"
    password: "production-db-password"
  
  # API Keys
  api:
    key: "production-api-key"
    jwtSecret: "production-jwt-secret-key"
  
  # External Service Credentials
  external:
    apiKey: "production-external-api-key"
    apiSecret: "production-external-api-secret"
  
  # OAuth Credentials
  oauth:
    clientId: "production-oauth-client-id"
    clientSecret: "production-oauth-client-secret"
  
  # Encryption Keys
  encryption:
    key: "production-encryption-key"
    signingKey: "production-signing-key"
  
  # Third-party Service Keys
  aws:
    accessKey: "production-aws-access-key"
    secretKey: "production-aws-secret-key"
  
  # Monitoring and Logging
  monitoring:
    prometheusToken: "production-prometheus-token"
    grafanaApiKey: "production-grafana-api-key"
  
  # Backup and Storage
  storage:
    backupEncryptionKey: "production-backup-encryption-key"
    accessKey: "production-storage-access-key"
    secretKey: "production-storage-secret-key"
  
  # SSL/TLS Certificates
  ssl:
    cert: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t"  # Base64 encoded SSL certificate
    key: "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0t"  # Base64 encoded SSL private key
  
  # Application-specific secrets
  app:
    adminPassword: "production-admin-password"
    userDefaultPassword: "production-user-default-password"
  
  # Feature Flags (sensitive)
  features:
    betaFeaturesEnabled: "false"
    debugMode: "false"
  
  # Rate Limiting
  rateLimit:
    key: "production-rate-limit-key"
  
  # Session Configuration
  session:
    secret: "production-session-secret-key"
  
  # Cache Configuration
  cache:
    password: "production-cache-password"
  
  # Message Queue
  messageQueue:
    rabbitmqPassword: "production-rabbitmq-password"
    kafkaPassword: "production-kafka-password"
  
  # Webhook Secrets
  webhooks:
    secret: "production-webhook-secret"
    githubSecret: "production-github-webhook-secret"
  
  # Analytics and Tracking
  analytics:
    key: "production-analytics-key"
    trackingId: "production-tracking-id"
  
  # Payment Processing
  payment:
    stripeSecretKey: "production-stripe-secret-key"
    paypalClientSecret: "production-paypal-client-secret"
  
  # CDN and Media
  media:
    cdnAccessKey: "production-cdn-access-key"
    storageKey: "production-media-storage-key"
  
  # Notification Services
  notifications:
    pushNotificationKey: "production-push-notification-key"
    smsApiKey: "production-sms-api-key"
  
  # Search and Indexing
  search:
    elasticsearchPassword: "production-elasticsearch-password"
    solrPassword: "production-solr-password"
  
  # Machine Learning Services
  ml:
    apiKey: "production-ml-api-key"
    aiServiceToken: "production-ai-service-token"
  
  # Compliance and Audit
  compliance:
    auditEncryptionKey: "production-audit-encryption-key"
    complianceToken: "production-compliance-token"

# Health checks configuration
healthCheck:
  livenessProbe:
    httpGet:
      path: /health
      port: 8080
      scheme: HTTP
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1
  
  readinessProbe:
    httpGet:
      path: /ready
      port: 8080
      scheme: HTTP
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3
    successThreshold: 1
  
  startupProbe:
    httpGet:
      path: /health
      port: 8080
      scheme: HTTP
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 30
    successThreshold: 1

# Volume configuration
volumes:
  config:
    mountPath: /app/config
    readOnly: true
  
  logs:
    mountPath: /app/logs
  
  tmp:
    mountPath: /tmp
  
  uploads:
    mountPath: /app/uploads

# Persistent volume configuration
persistence:
  enabled: true
  storageClass: "fast-ssd"
  accessMode: ReadWriteOnce
  size: 50Gi
  annotations:
    volume.beta.kubernetes.io/storage-class: "fast-ssd"

# Network policy configuration
networkPolicy:
  enabled: true
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
        - podSelector:
            matchLabels:
              app: nginx-ingress
      ports:
        - protocol: TCP
          port: 8080
  egress:
    - to: []
      ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53

# Pod disruption budget
podDisruptionBudget:
  enabled: true
  minAvailable: 2
  maxUnavailable: 1

# Termination grace period
terminationGracePeriodSeconds: 30

# DNS policy
dnsPolicy: ClusterFirst
