---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-app-config
  namespace: flask-app
data:
  DATABASE_PATH: "/app/data/users.db"
  DEBUG: "false"
  HOST: "0.0.0.0"
  PORT: "5000"
  LOG_LEVEL: "INFO"
