---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: flask-app-pv
  labels:
    app: flask-user-app
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /tmp/flask-app-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flask-app-pvc
  namespace: flask-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
