version: '3.8'

services:
  sqlite3:
    build: .
    image: sqlite3-test:latest
    container_name: sqlite3-test-container
    volumes:
      - ./databases:/app/databases
      - ./sql-scripts:/app/sql-scripts
      - ./data:/app/data
    working_dir: /app
    # Override default command to keep container running
    command: tail -f /dev/null
    
  sqlite3-interactive:
    image: cleanstart/sqlite3:latest-dev
    container_name: sqlite3-interactive
    volumes:
      - ./databases:/app/databases
      - ./sql-scripts:/app/sql-scripts
      - ./data:/app/data
    working_dir: /app
    stdin_open: true
    tty: true
    command: sqlite3 /app/databases/test.db