apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: aws-cli-app
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  AWS_SESSION_TOKEN: ""


