apiVersion: v1
kind: Service
metadata:
  name: go-web-service
  labels:
    app: go-web-app
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: go-web-app
---
apiVersion: v1
kind: Service
metadata:
  name: go-web-service-nodeport
  labels:
    app: go-web-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30080
    protocol: TCP
    name: http
  selector:
    app: go-web-app
