apiVersion: v1
kind: Service
metadata:
  name: busybox-http-server-service
  namespace: busybox-sample
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: busybox-http-server
