apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: require-labels
spec:
  rules:
    - name: check-labels
      match:
        resources:
          kinds:
            - Pod
      validate:
        message: "All pods must have labels."
        pattern:
          metadata:
            labels:
              app: "?*"
