apiVersion: batch/v1
kind: Job
metadata:
  name: helm-version-check
  namespace: helm-test
  labels:
    app: helm-test
spec:
  template:
    metadata:
      labels:
        job-name: helm-version-check
    spec:
      restartPolicy: Never
      containers:
      - name: helm
        image: cleanstart/helm:latest-dev
        command: ["helm"]
        args:
          - "search"
          - "hub"
          - "nginx"
                  
        securityContext:
          runAsUser: 1000
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
  
  backoffLimit: 3
  ttlSecondsAfterFinished: 300
