services:
  # PostgreSQL Database
  db:
    image: cleanstart/postgres:latest-dev
    container_name: postgres-sample-db
    environment:
      POSTGRES_DB: helloworld
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # Flask Web Application
  web:
    build: .
    container_name: postgres-sample-web
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_NAME: helloworld
      DB_USER: postgres
      DB_PASSWORD: password
      DB_PORT: 5432
      FLASK_ENV: production
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
