# Logstash Exporter Configuration
# This is a basic configuration for monitoring Logstash

# Logstash Exporter settings
logstash:
  # Logstash API endpoint
  address: "http://logstash:9600"
  
  # Timeout for API calls
  timeout: 5s
  
  # Metrics collection interval
  interval: 30s

# Prometheus metrics settings
metrics:
  # Enable/disable specific metric groups
  node_stats: true
  node_info: true
  pipelines: true
  
  # Custom labels to add to all metrics
  labels:
    environment: "development"
    cluster: "local"

# HTTP server settings
server:
  # Port for the metrics endpoint
  port: 9198
  
  # Address to bind to
  address: "0.0.0.0"
  
  # Path for metrics endpoint
  path: "/metrics"

# Logging configuration
logging:
  level: "info"
  format: "json"
