apiVersion: v1
kind: Service
metadata:
  name: minio-app-service
  namespace: minio-app
spec:
  type: LoadBalancer
  ports:
  - port: 9000
    targetPort: 9000
    name: api
  - port: 9090
    targetPort: 9090
    name: console
  selector:
    app: minio-app
