services:
  # A one-shot curl request to httpbin
  curl-client:
    image: cleanstart/curl:latest
    container_name: curl-client
    command: ["https://httpbin.org/get", "--retry", "999999", "--retry-delay", "10"]


  # A curl POST request
  curl-poster:
    image: cleanstart/curl:latest
    container_name: curl-poster
    command: ["-X", "POST", "https://httpbin.org/post", "-d", "name=komal"]


  # A "monitor" that repeats every 10 seconds
  # Since no shell is available, use curl's --retry and --max-time to simulate checks
  curl-monitor:
    image: cleanstart/curl:latest
    container_name: curl-monitor
    command: ["--retry", "999999", "--retry-delay", "10", "-s", "-o", "/dev/null", "-w", "HTTP %{http_code}\n", "https://httpbin.org/status/200"]

